[tool.poetry]
name = "dbgpy"
version = "0.1.0"
description = "Python implementation of Rust's dbg! macro using CSTs"
authors = ["Marcel Rød <marcelroed@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
torch = {version = "^1", optional = true}
astunparse = {version = "^1", markers = "python_version<'3.9'"}

[tool.poetry.dev-dependencies]
pytest = "^7"
black = "^22"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
